function(add_modules)
  foreach(mod IN LISTS ARGN)
    if(mod STREQUAL "tests")
      set(tests_root "${CMAKE_CURRENT_SOURCE_DIR}/tests")
      if(EXISTS "${tests_root}/CMakeLists.txt")
        add_subdirectory(tests)
      elseif(EXISTS "${tests_root}")
        file(GLOB children LIST_DIRECTORIES TRUE "${tests_root}/*")
        foreach(child IN LISTS children)
          if(IS_DIRECTORY "${child}" AND EXISTS "${child}/CMakeLists.txt")
            file(RELATIVE_PATH rel "${CMAKE_CURRENT_SOURCE_DIR}" "${child}")
            add_subdirectory("${rel}")
          endif()
        endforeach()
      else()
        message(STATUS "[AddModules] no tests/ directory in ${CMAKE_CURRENT_SOURCE_DIR}")
      endif()
    else()
      set(dir "${CMAKE_CURRENT_SOURCE_DIR}/${mod}")
      if(EXISTS "${dir}/CMakeLists.txt")
        add_subdirectory("${mod}")
      else()
        message(FATAL_ERROR "[AddModules] '${mod}/CMakeLists.txt' not found in ${CMAKE_CURRENT_SOURCE_DIR}")
      endif()
    endif()
  endforeach()
endfunction()
