# must：
#   DIR_TARGET_NAME, DIR_TARGET_TYPE (EXECUTABLE|LIBRARY)
# option：
#   DIR_LIBRARY_KIND, DIR_PUBLIC_DEPS, DIR_PRIVATE_DEPS, DIR_INTERFACE_DEPS
#   DIR_ALIAS_PREFIX(default project), DIR_INCLUDE_CURRENT(default ON)
#   DIR_SOURCES, DIR_HEADERS, DIR_ENABLE_FILE_SET(default ON, cmake>=3.23)
#   DIR_POSITION_INDEPENDENT(lib default ON), DIR_CXX_STD(default cxx_std_20)
#   DIR_REGISTER_TEST(default OFF), DIR_TEST_NAME
#   DIR_ENABLE_INSTALL(default OFF), DIR_EXPORT_NAME(default PROJECT_EXPORT_NAME or <proj>Targets)
include(GNUInstallDirs)

if(NOT DEFINED DIR_TARGET_NAME)
  message(FATAL_ERROR "[AddTarget] DIR_TARGET_NAME is required")
endif()

if(NOT DEFINED DIR_TARGET_TYPE)
  message(FATAL_ERROR "[AddTarget] DIR_TARGET_TYPE is required (EXECUTABLE or LIBRARY)")
endif()

if(NOT DEFINED DIR_ALIAS_PREFIX)      
  set(DIR_ALIAS_PREFIX "project")        
endif()
if(NOT DEFINED DIR_INCLUDE_CURRENT)  
  set(DIR_INCLUDE_CURRENT ON)            
endif()
if(NOT DEFINED DIR_ENABLE_FILE_SET)   
  set(DIR_ENABLE_FILE_SET ON)            
endif()
if(NOT DEFINED DIR_CXX_STD)           
  set(DIR_CXX_STD cxx_std_20)            
endif()
if(NOT DEFINED DIR_ENABLE_INSTALL)    
  set(DIR_ENABLE_INSTALL OFF)            
endif()

if(NOT DEFINED DIR_REGISTER_TEST)
  if(CMAKE_CURRENT_SOURCE_DIR MATCHES "/tests(/|$)")
    set(DIR_REGISTER_TEST ON)
  else()
    set(DIR_REGISTER_TEST OFF)
  endif()
endif()

if(NOT DEFINED DIR_SOURCES)
  message(FATAL_ERROR "[AddTarget] DIR_SOURCES is required to avoid glob-based reconfigure")
endif()

if(NOT DEFINED DIR_HEADERS)
  set(DIR_HEADERS "")
endif()

if(DIR_TARGET_TYPE STREQUAL "EXECUTABLE")
  add_executable(${DIR_TARGET_NAME} ${DIR_SOURCES} ${DIR_HEADERS})
elseif(DIR_TARGET_TYPE STREQUAL "LIBRARY")
  if(DEFINED DIR_LIBRARY_KIND)
    add_library(${DIR_TARGET_NAME} ${DIR_LIBRARY_KIND} ${DIR_SOURCES} ${DIR_HEADERS})
  else()
    add_library(${DIR_TARGET_NAME} ${DIR_SOURCES} ${DIR_HEADERS})
  endif()
else()
  message(FATAL_ERROR "[AddTarget] Unknown DIR_TARGET_TYPE='${DIR_TARGET_TYPE}'")
endif()

if(DIR_TARGET_TYPE STREQUAL "LIBRARY")
  add_library(${DIR_ALIAS_PREFIX}::${DIR_TARGET_NAME} ALIAS ${DIR_TARGET_NAME})
endif()

target_compile_features(${DIR_TARGET_NAME} PUBLIC ${DIR_CXX_STD})

if(DIR_INCLUDE_CURRENT)
  if(DIR_TARGET_TYPE STREQUAL "LIBRARY")
    target_include_directories(${DIR_TARGET_NAME}
      PUBLIC
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>
        $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/${DIR_TARGET_NAME}>
    )
  else()
    target_include_directories(${DIR_TARGET_NAME}
      PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}
    )
  endif()
endif()

if(DIR_TARGET_TYPE STREQUAL "LIBRARY")
  if(NOT DEFINED DIR_POSITION_INDEPENDENT)
    set(DIR_POSITION_INDEPENDENT ON)
  endif()
  set_target_properties(${DIR_TARGET_NAME} PROPERTIES POSITION_INDEPENDENT_CODE ${DIR_POSITION_INDEPENDENT})
endif()

if(DIR_ENABLE_FILE_SET AND CMAKE_VERSION VERSION_GREATER_EQUAL "3.23" AND DIR_HEADERS)
  target_sources(${DIR_TARGET_NAME}
    PUBLIC
      FILE_SET HEADERS
      BASE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}
      FILES ${DIR_HEADERS}
  )
endif()

if(DEFINED DIR_PUBLIC_DEPS OR DEFINED DIR_PRIVATE_DEPS OR DEFINED DIR_INTERFACE_DEPS)
  target_link_libraries(${DIR_TARGET_NAME}
    PUBLIC    ${DIR_PUBLIC_DEPS}
    PRIVATE   ${DIR_PRIVATE_DEPS}
    INTERFACE ${DIR_INTERFACE_DEPS}
  )
endif()

if(DIR_REGISTER_TEST AND (DIR_TARGET_TYPE STREQUAL "EXECUTABLE"))
  if(NOT DEFINED DIR_TEST_NAME)
    set(DIR_TEST_NAME ${DIR_TARGET_NAME})
  endif()
  add_test(NAME ${DIR_TEST_NAME} COMMAND ${DIR_TARGET_NAME})
endif()

if(DIR_ENABLE_INSTALL)
  if(NOT DEFINED DIR_EXPORT_NAME)
    if(DEFINED PROJECT_EXPORT_NAME)
      set(DIR_EXPORT_NAME "${PROJECT_EXPORT_NAME}")
    else()
      set(DIR_EXPORT_NAME "${PROJECT_NAME}Targets")
    endif()
  endif()

  if(DIR_TARGET_TYPE STREQUAL "EXECUTABLE")
    install(TARGETS ${DIR_TARGET_NAME}
      EXPORT ${DIR_EXPORT_NAME}
      RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
    )
  elseif(DIR_TARGET_TYPE STREQUAL "LIBRARY")
    if(DIR_ENABLE_FILE_SET AND CMAKE_VERSION VERSION_GREATER_EQUAL "3.23" AND DIR_HEADERS)
      install(TARGETS ${DIR_TARGET_NAME}
        EXPORT ${DIR_EXPORT_NAME}
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
        FILE_SET HEADERS DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${DIR_TARGET_NAME}
      )
    else()
      install(TARGETS ${DIR_TARGET_NAME}
        EXPORT ${DIR_EXPORT_NAME}
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
      )
      if(DIR_HEADERS)
        install(FILES ${DIR_HEADERS} DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${DIR_TARGET_NAME})
      endif()
    endif()
  endif()
endif()

unset(DIR_TARGET_NAME)
unset(DIR_TARGET_TYPE)
unset(DIR_LIBRARY_KIND)
unset(DIR_PUBLIC_DEPS)
unset(DIR_PRIVATE_DEPS)
unset(DIR_INTERFACE_DEPS)
unset(DIR_ALIAS_PREFIX)
unset(DIR_INCLUDE_CURRENT)
unset(DIR_SOURCES)
unset(DIR_HEADERS)
unset(DIR_ENABLE_FILE_SET)
unset(DIR_POSITION_INDEPENDENT)
unset(DIR_CXX_STD)
unset(DIR_REGISTER_TEST)
unset(DIR_TEST_NAME)
unset(DIR_ENABLE_INSTALL)
unset(DIR_EXPORT_NAME)
