# AddWorkspaces.cmake — recursively discover subprojects and add_subdirectory them.
function(add_workspace_projects)
  set(options)
  set(oneValueArgs ROOT MODE IGNORE_REGEX MAX_DEPTH)
  set(multiValueArgs ONLY EXCLUDE EXCLUDE_DIR_NAMES STOP_MARKERS)
  cmake_parse_arguments(AWP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if(NOT AWP_ROOT)
    set(AWP_ROOT "${CMAKE_SOURCE_DIR}/projects")
  endif()
  if(NOT EXISTS "${AWP_ROOT}")
    message(FATAL_ERROR "[add_workspace_projects] ROOT not found: ${AWP_ROOT}")
  endif()

  if(NOT AWP_MODE)
    set(AWP_MODE "FIRST") # FIRST | ALL | LEAF
  endif()
  if(NOT DEFINED AWP_MAX_DEPTH)
    set(AWP_MAX_DEPTH 0)  # 0 = unlimited
  endif()
  if(NOT AWP_EXCLUDE_DIR_NAMES)
    set(AWP_EXCLUDE_DIR_NAMES ".git;build;cmake;.cache;out;dist;node_modules")
  endif()

  function(_awp_should_stop dir result)
    set(stop FALSE)
    foreach(m IN LISTS AWP_STOP_MARKERS)
      if(EXISTS "${dir}/${m}")
        set(stop TRUE)
        break()
      endif()
    endforeach()
    set(${result} ${stop} PARENT_SCOPE)
  endfunction()

  function(_awp_collect dir depth out_var)
    if(AWP_MAX_DEPTH GREATER 0 AND depth GREATER AWP_MAX_DEPTH)
      return()
    endif()

    get_filename_component(_name "${dir}" NAME)
    foreach(skip IN LISTS AWP_EXCLUDE_DIR_NAMES)
      if(_name STREQUAL "${skip}")
        return()
      endif()
    endforeach()

    if(AWP_IGNORE_REGEX)
      string(REGEX MATCH "${AWP_IGNORE_REGEX}" _m "${dir}")
      if(_m)
        return()
      endif()
    endif()

    _awp_should_stop("${dir}" _stop)
    if(_stop)
      return()
    endif()

    if(EXISTS "${dir}/CMakeLists.txt")
      set(_acc "${${out_var}}")
      list(APPEND _acc "${dir}")
      set(${out_var} "${_acc}" PARENT_SCOPE)
      if(AWP_MODE STREQUAL "FIRST")
        return()
      endif()
    endif()

    file(GLOB _children LIST_DIRECTORIES TRUE "${dir}/*")
    foreach(_c IN LISTS _children)
      if(NOT IS_DIRECTORY "${_c}")
        continue()
      endif()
      get_filename_component(_cname "${_c}" NAME)
      set(skip_child FALSE)
      foreach(skip IN LISTS AWP_EXCLUDE_DIR_NAMES)
        if(_cname STREQUAL "${skip}")
          set(skip_child TRUE)
          break()
        endif()
      endforeach()
      if(skip_child)
        continue()
      endif()
      if(AWP_IGNORE_REGEX)
        string(REGEX MATCH "${AWP_IGNORE_REGEX}" _m2 "${_c}")
        if(_m2)
          continue()
        endif()
      endif()
      math(EXPR nextdepth "${depth} + 1")
      _awp_collect("${_c}" ${nextdepth} ${out_var})
    endforeach()
  endfunction()

  set(_candidates)
  _awp_collect("${AWP_ROOT}" 0 _candidates)
  if(NOT _candidates)
    message(WARNING "[add_workspace_projects] No subprojects found under: ${AWP_ROOT}")
    return()
  endif()

  if(AWP_MODE STREQUAL "LEAF")
    set(_leafs)
    foreach(p IN LISTS _candidates)
      set(is_ancestor FALSE)
      foreach(q IN LISTS _candidates)
        if(p STREQUAL q)
          continue()
        endif()
        string(FIND "${q}" "${p}/" _pos)
        if(_pos EQUAL 0)
          set(is_ancestor TRUE)
          break()
        endif()
      endforeach()
      if(NOT is_ancestor)
        list(APPEND _leafs "${p}")
      endif()
    endforeach()
    set(_candidates "${_leafs}")
  endif()

  set(_filtered)
  foreach(p IN LISTS _candidates)
    get_filename_component(name "${p}" NAME)
    set(ok TRUE)
    if(AWP_ONLY)
      list(FIND AWP_ONLY "${name}" _idx_only)
      if(_idx_only EQUAL -1) 
      set(ok FALSE) 
      endif()
    endif()
    if(AWP_EXCLUDE)
      list(FIND AWP_EXCLUDE "${name}" _idx_ex)
      if(NOT _idx_ex EQUAL -1) 
      set(ok FALSE) 
      endif()
    endif()
    if(ok) 
    list(APPEND _filtered "${p}") 
    endif()
  endforeach()

  list(REMOVE_DUPLICATES _filtered)
  list(SORT _filtered)

  get_property(_already GLOBAL PROPERTY AWP_ADDED_DIRS)
  if(NOT _already)
    set(_already "")
  endif()

  foreach(p IN LISTS _filtered)
    file(RELATIVE_PATH rel "${CMAKE_SOURCE_DIR}" "${p}")
    list(FIND _already "${rel}" _idx)
    if(_idx EQUAL -1)
      unset(PROJECT_EXPORT_NAME CACHE) # avoid leaking to subprojects
      add_subdirectory("${rel}")
      list(APPEND _already "${rel}")
    endif()
  endforeach()

  set_property(GLOBAL PROPERTY AWP_ADDED_DIRS "${_already}")
endfunction()
