# usage：
#   include(AddWorkspaces)
#   add_workspace_projects(
#     ROOT "${CMAKE_SOURCE_DIR}/projects"
#     MODE LEAF                  # FIRST | ALL | LEAF（default FIRST）
#     ONLY   netlib utils        # Optional: Build only these (end-level directory names)
#     EXCLUDE legacy             # Optional: Exclude these (end-level directory names)
#     EXCLUDE_DIR_NAMES ".git;build;cmake;.cache;out;dist;node_modules"  # optional
#     IGNORE_REGEX ".*experimental.*"  # Optional: Full path regular expression
#     MAX_DEPTH 0                # Optional: 0 - No limit; >0 - Limit the number of directory levels starting from the ROOT directory
#   )

function(add_workspace_projects)
  set(options)
  set(oneValueArgs ROOT MODE IGNORE_REGEX MAX_DEPTH)
  set(multiValueArgs ONLY EXCLUDE EXCLUDE_DIR_NAMES)
  cmake_parse_arguments(AWP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if(NOT AWP_ROOT)
    set(AWP_ROOT "${CMAKE_SOURCE_DIR}/projects")
  endif()
  if(NOT EXISTS "${AWP_ROOT}")
    message(FATAL_ERROR "[add_workspace_projects] ROOT not found: ${AWP_ROOT}")
  endif()

  if(NOT AWP_MODE)               # FIRST=remain shallowest；ALL LEAF=deepest
    set(AWP_MODE "FIRST")
  endif()
  if(NOT DEFINED AWP_MAX_DEPTH)
    set(AWP_MAX_DEPTH 0)
  endif()
  if(NOT AWP_EXCLUDE_DIR_NAMES)
    set(AWP_EXCLUDE_DIR_NAMES ".git;build;cmake;.cache;out;dist;node_modules")
  endif()

  file(GLOB_RECURSE _cmakes "${AWP_ROOT}/CMakeLists.txt")
  if(NOT _cmakes)
    message(WARNING "[add_workspace_projects] No CMakeLists.txt found under: ${AWP_ROOT}")
    return()
  endif()

  set(_candidates)
  foreach(f IN LISTS _cmakes)
    get_filename_component(d "${f}" DIRECTORY)
    if(AWP_IGNORE_REGEX)
      string(REGEX MATCH "${AWP_IGNORE_REGEX}" _m "${d}")
      if(_m) 
        continue()
      endif()
    endif()
    set(_skip FALSE)
    foreach(name IN LISTS AWP_EXCLUDE_DIR_NAMES)
      if(d MATCHES "/${name}(/|$)")
        set(_skip TRUE)
        break()
      endif()
    endforeach()
    if(_skip)
      continue()
    endif()
    if(AWP_MAX_DEPTH GREATER 0)
      file(RELATIVE_PATH rel "${AWP_ROOT}" "${d}")
      if(rel STREQUAL ".")
        set(depth 0)
      else()
        string(REPLACE "/" ";" parts "${rel}")
        list(LENGTH parts depth)
      endif()
      if(depth GREATER AWP_MAX_DEPTH)
        continue()
      endif()
    endif()
    list(APPEND _candidates "${d}")
  endforeach()

  if(NOT _candidates)
    message(WARNING "[add_workspace_projects] No candidates after filters.")
    return()
  endif()

  list(REMOVE_DUPLICATES _candidates)
  list(SORT _candidates)

  set(_prefer)
  foreach(d IN LISTS _candidates)
    file(READ "${d}/CMakeLists.txt" _cfg LIMIT 4096)
    string(REGEX MATCH "^[ \t]*project\\s*\\(" _has_proj "${_cfg}")
    if(_has_proj)
      list(APPEND _prefer "${d}")
    endif()
  endforeach()
  if(_prefer)
    set(_candidates "${_prefer}")
  endif()

  if(AWP_MODE STREQUAL "LEAF")
    set(_out)
    foreach(p IN LISTS _candidates)
      set(is_ancestor FALSE)
      foreach(q IN LISTS _candidates)
        if(p STREQUAL q) 
          continue() 
        endif()
        string(FIND "${q}" "${p}/" pos)
        if(pos EQUAL 0) 
          set(is_ancestor TRUE)
          break()
        endif()
      endforeach()
      if(NOT is_ancestor) 
        list(APPEND _out "${p}") 
      endif()
    endforeach()
    set(_candidates "${_out}")
  elseif(AWP_MODE STREQUAL "FIRST")
    set(_out)
    foreach(p IN LISTS _candidates)
      set(has_ancestor FALSE)
      foreach(q IN LISTS _candidates)
        if(p STREQUAL q) 
          continue() 
        endif()
        string(FIND "${p}" "${q}/" pos)
        if(pos EQUAL 0) 
          set(has_ancestor TRUE)
          break()
        endif()
      endforeach()
      if(NOT has_ancestor) 
        list(APPEND _out "${p}") 
      endif()
    endforeach()
    set(_candidates "${_out}")
  endif()

  set(_final)
  foreach(p IN LISTS _candidates)
    get_filename_component(name "${p}" NAME)
    set(ok TRUE)
    if(AWP_ONLY)
      list(FIND AWP_ONLY "${name}" _idx_only)
      if(_idx_only EQUAL -1) 
        set(ok FALSE) 
      endif()
    endif()
    if(AWP_EXCLUDE)
      list(FIND AWP_EXCLUDE "${name}" _idx_ex)
      if(NOT _idx_ex EQUAL -1) 
        set(ok FALSE) 
      endif()
    endif()
    if(ok) 
      list(APPEND _final "${p}") 
    endif()
  endforeach()

  list(REMOVE_DUPLICATES _final)
  list(SORT _final)

  if(NOT _final)
    message(WARNING "[add_workspace_projects] Found candidates but all filtered out by ONLY/EXCLUDE.")
    return()
  endif()

  get_property(_already GLOBAL PROPERTY AWP_ADDED_DIRS)
  if(NOT _already) 
    set(_already "") 
  endif()

  foreach(p IN LISTS _final)
    file(RELATIVE_PATH rel "${CMAKE_SOURCE_DIR}" "${p}")
    list(FIND _already "${rel}" _idx)
    if(_idx EQUAL -1)
      message(STATUS "[AddWorkspaces] add_subdirectory(${rel})")
      unset(PROJECT_EXPORT_NAME CACHE)
      add_subdirectory("${rel}")
      list(APPEND _already "${rel}")
    endif()
  endforeach()
  set_property(GLOBAL PROPERTY AWP_ADDED_DIRS "${_already}")
endfunction()
