# 用法：
#   include(AddWorkspaces)
#   add_workspace_projects(
#     ROOT "${CMAKE_SOURCE_DIR}/projects"
#     MODE LEAF                  # FIRST | ALL | LEAF（默认 FIRST）
#     DIRS  pathA pathB          # 可选：显式目录（相对 CMAKE_SOURCE_DIR 或绝对路径）
#     ONLY   netlib utils        # 可选：仅包含这些末级目录名
#     EXCLUDE legacy             # 可选：排除这些末级目录名
#     EXCLUDE_DIR_NAMES ".git;build;cmake;.cache;out;dist;node_modules"
#     IGNORE_REGEX ".*experimental.*"  # 可选：全路径正则排除
#     MAX_DEPTH 0                # 可选：0=不限；>0=从 ROOT 限制深度
#   )

function(add_workspace_projects)
  # 解析参数，用于工作区发现与过滤。
  set(options)
  set(oneValueArgs ROOT MODE IGNORE_REGEX MAX_DEPTH)
  set(multiValueArgs ONLY EXCLUDE EXCLUDE_DIR_NAMES DIRS)
  cmake_parse_arguments(AWP "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if(NOT AWP_ROOT)
    # 默认工作区根目录。
    set(AWP_ROOT "${CMAKE_SOURCE_DIR}/projects")
  endif()
  if(NOT EXISTS "${AWP_ROOT}")
    message(FATAL_ERROR "[add_workspace_projects] ROOT not found: ${AWP_ROOT}")
  endif()

  if(NOT AWP_MODE)               # FIRST=最浅层，ALL=全部，LEAF=最深层
    set(AWP_MODE "FIRST")
  endif()
  if(NOT DEFINED AWP_MAX_DEPTH)
    set(AWP_MAX_DEPTH 0)
  endif()
  if(NOT AWP_EXCLUDE_DIR_NAMES)
    set(AWP_EXCLUDE_DIR_NAMES ".git;build;cmake;.cache;out;dist;node_modules")
  endif()

  set(_candidates)
  if(AWP_DIRS)
    # 显式列表模式：不扫描、不 glob。
    foreach(d IN LISTS AWP_DIRS)
      if(IS_ABSOLUTE "${d}")
        set(_cand "${d}")
      else()
        set(_cand "${CMAKE_SOURCE_DIR}/${d}")
      endif()
      if(EXISTS "${_cand}/CMakeLists.txt")
        list(APPEND _candidates "${_cand}")
      else()
        message(WARNING "[add_workspace_projects] CMakeLists.txt not found in: ${_cand}")
      endif()
    endforeach()
  else()
    # 扫描工作区根目录下的 CMakeLists.txt。
    file(GLOB_RECURSE _cmakes "${AWP_ROOT}/CMakeLists.txt")
    if(NOT _cmakes)
      message(WARNING "[add_workspace_projects] No CMakeLists.txt found under: ${AWP_ROOT}")
      return()
    endif()

    foreach(f IN LISTS _cmakes)
      get_filename_component(d "${f}" DIRECTORY)
      if(AWP_IGNORE_REGEX)
        string(REGEX MATCH "${AWP_IGNORE_REGEX}" _m "${d}")
        if(_m)
          continue()
        endif()
      endif()
      set(_skip FALSE)
      foreach(name IN LISTS AWP_EXCLUDE_DIR_NAMES)
        if(d MATCHES "/${name}(/|$)")
          set(_skip TRUE)
          break()
        endif()
      endforeach()
      if(_skip)
        continue()
      endif()
      if(AWP_MAX_DEPTH GREATER 0)
        file(RELATIVE_PATH rel "${AWP_ROOT}" "${d}")
        if(rel STREQUAL ".")
          set(depth 0)
        else()
          string(REPLACE "/" ";" parts "${rel}")
          list(LENGTH parts depth)
        endif()
        if(depth GREATER AWP_MAX_DEPTH)
          continue()
        endif()
      endif()
      list(APPEND _candidates "${d}")
    endforeach()
  endif()

  if(NOT _candidates)
    message(WARNING "[add_workspace_projects] No candidates after filters.")
    return()
  endif()

  list(REMOVE_DUPLICATES _candidates)
  list(SORT _candidates)

  # 优先选择包含 project() 的目录。
  set(_prefer)
  foreach(d IN LISTS _candidates)
    file(READ "${d}/CMakeLists.txt" _cfg LIMIT 4096)
    string(REGEX MATCH "^[ \t]*project\\s*\\(" _has_proj "${_cfg}")
    if(_has_proj)
      list(APPEND _prefer "${d}")
    endif()
  endforeach()
  if(_prefer)
    set(_candidates "${_prefer}")
  endif()

  if(AWP_MODE STREQUAL "LEAF")
    # 仅保留最深层（叶子）目录。
    set(_out)
    foreach(p IN LISTS _candidates)
      set(is_ancestor FALSE)
      foreach(q IN LISTS _candidates)
        if(p STREQUAL q)
          continue()
        endif()
        string(FIND "${q}" "${p}/" pos)
        if(pos EQUAL 0)
          set(is_ancestor TRUE)
          break()
        endif()
      endforeach()
      if(NOT is_ancestor)
        list(APPEND _out "${p}")
      endif()
    endforeach()
    set(_candidates "${_out}")
  elseif(AWP_MODE STREQUAL "FIRST")
    # 仅保留最浅层（顶层）目录。
    set(_out)
    foreach(p IN LISTS _candidates)
      set(has_ancestor FALSE)
      foreach(q IN LISTS _candidates)
        if(p STREQUAL q)
          continue()
        endif()
        string(FIND "${p}" "${q}/" pos)
        if(pos EQUAL 0)
          set(has_ancestor TRUE)
          break()
        endif()
      endforeach()
      if(NOT has_ancestor)
        list(APPEND _out "${p}")
      endif()
    endforeach()
    set(_candidates "${_out}")
  endif()

  set(_final)
  foreach(p IN LISTS _candidates)
    get_filename_component(name "${p}" NAME)
    set(ok TRUE)
    if(AWP_ONLY)
      list(FIND AWP_ONLY "${name}" _idx_only)
      if(_idx_only EQUAL -1)
        set(ok FALSE)
      endif()
    endif()
    if(AWP_EXCLUDE)
      list(FIND AWP_EXCLUDE "${name}" _idx_ex)
      if(NOT _idx_ex EQUAL -1)
        set(ok FALSE)
      endif()
    endif()
    if(ok)
      list(APPEND _final "${p}")
    endif()
  endforeach()

  list(REMOVE_DUPLICATES _final)
  list(SORT _final)

  if(NOT _final)
    message(WARNING "[add_workspace_projects] Found candidates but all filtered out by ONLY/EXCLUDE.")
    return()
  endif()

  get_property(_already GLOBAL PROPERTY AWP_ADDED_DIRS)
  if(NOT _already)
    set(_already "")
  endif()

  # 仅添加一次，并记录到全局属性。
  foreach(p IN LISTS _final)
    file(RELATIVE_PATH rel "${CMAKE_SOURCE_DIR}" "${p}")
    list(FIND _already "${rel}" _idx)
    if(_idx EQUAL -1)
      message(STATUS "[AddWorkspaces] add_subdirectory(${rel})")
      unset(PROJECT_EXPORT_NAME CACHE)
      add_subdirectory("${rel}")
      list(APPEND _already "${rel}")
    endif()
  endforeach()
  set_property(GLOBAL PROPERTY AWP_ADDED_DIRS "${_already}")
endfunction()
