# Reports.cmake
# Adds convenience targets for build and test reports.

set(REPORTS_DIR "${CMAKE_BINARY_DIR}/reports")

add_custom_target(report-build
  COMMAND ${CMAKE_COMMAND} -E make_directory "${REPORTS_DIR}"
  COMMAND ${CMAKE_COMMAND}
    -DREPORTS_DIR="${REPORTS_DIR}"
    -DREPORT_BUILD_DIR="${CMAKE_BINARY_DIR}"
    -DREPORT_SOURCE_DIR="${CMAKE_SOURCE_DIR}"
    -DREPORT_PROJECT_NAME="${PROJECT_NAME}"
    -DREPORT_GENERATOR="${CMAKE_GENERATOR}"
    -DREPORT_BUILD_TYPE="${CMAKE_BUILD_TYPE}"
    -DREPORT_CONFIGS="${CMAKE_CONFIGURATION_TYPES}"
    -DREPORT_TESTS_INCLUDED=false
    -DREPORT_COMPILER_CXX="${CMAKE_CXX_COMPILER}"
    -DREPORT_COMPILER_CXX_ID="${CMAKE_CXX_COMPILER_ID}"
    -DREPORT_COMPILER_CXX_VERSION="${CMAKE_CXX_COMPILER_VERSION}"
    -DREPORT_SYSTEM_NAME="${CMAKE_SYSTEM_NAME}"
    -DREPORT_SYSTEM_VERSION="${CMAKE_SYSTEM_VERSION}"
    -DREPORT_SYSTEM_PROCESSOR="${CMAKE_SYSTEM_PROCESSOR}"
    -P "${CMAKE_SOURCE_DIR}/cmake/BuildReport.cmake"
  COMMENT "Generate build report"
)

set(_ctest_cmd ${CMAKE_CTEST_COMMAND} --output-on-failure --output-log "${REPORTS_DIR}/tests.log")
if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.21")
  list(APPEND _ctest_cmd --output-junit "${REPORTS_DIR}/tests.junit.xml")
endif()

add_custom_target(report-test
  COMMAND ${CMAKE_COMMAND} -E make_directory "${REPORTS_DIR}"
  COMMAND ${_ctest_cmd}
  WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
  COMMAND ${CMAKE_COMMAND}
    -DREPORTS_DIR="${REPORTS_DIR}"
    -DREPORT_BUILD_DIR="${CMAKE_BINARY_DIR}"
    -DREPORT_SOURCE_DIR="${CMAKE_SOURCE_DIR}"
    -DREPORT_PROJECT_NAME="${PROJECT_NAME}"
    -DREPORT_GENERATOR="${CMAKE_GENERATOR}"
    -DREPORT_BUILD_TYPE="${CMAKE_BUILD_TYPE}"
    -DREPORT_CONFIGS="${CMAKE_CONFIGURATION_TYPES}"
    -DREPORT_TESTS_INCLUDED=true
    -DREPORT_COMPILER_CXX="${CMAKE_CXX_COMPILER}"
    -DREPORT_COMPILER_CXX_ID="${CMAKE_CXX_COMPILER_ID}"
    -DREPORT_COMPILER_CXX_VERSION="${CMAKE_CXX_COMPILER_VERSION}"
    -DREPORT_SYSTEM_NAME="${CMAKE_SYSTEM_NAME}"
    -DREPORT_SYSTEM_VERSION="${CMAKE_SYSTEM_VERSION}"
    -DREPORT_SYSTEM_PROCESSOR="${CMAKE_SYSTEM_PROCESSOR}"
    -P "${CMAKE_SOURCE_DIR}/cmake/BuildReport.cmake"
  COMMENT "Generate test report"
)

add_custom_target(report-all
  COMMAND ${CMAKE_COMMAND} -E make_directory "${REPORTS_DIR}"
  COMMAND ${_ctest_cmd}
  WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
  COMMAND ${CMAKE_COMMAND}
    -DREPORTS_DIR="${REPORTS_DIR}"
    -DREPORT_BUILD_DIR="${CMAKE_BINARY_DIR}"
    -DREPORT_SOURCE_DIR="${CMAKE_SOURCE_DIR}"
    -DREPORT_PROJECT_NAME="${PROJECT_NAME}"
    -DREPORT_GENERATOR="${CMAKE_GENERATOR}"
    -DREPORT_BUILD_TYPE="${CMAKE_BUILD_TYPE}"
    -DREPORT_CONFIGS="${CMAKE_CONFIGURATION_TYPES}"
    -DREPORT_TESTS_INCLUDED=true
    -DREPORT_COMPILER_CXX="${CMAKE_CXX_COMPILER}"
    -DREPORT_COMPILER_CXX_ID="${CMAKE_CXX_COMPILER_ID}"
    -DREPORT_COMPILER_CXX_VERSION="${CMAKE_CXX_COMPILER_VERSION}"
    -DREPORT_SYSTEM_NAME="${CMAKE_SYSTEM_NAME}"
    -DREPORT_SYSTEM_VERSION="${CMAKE_SYSTEM_VERSION}"
    -DREPORT_SYSTEM_PROCESSOR="${CMAKE_SYSTEM_PROCESSOR}"
    -P "${CMAKE_SOURCE_DIR}/cmake/BuildReport.cmake"
  COMMENT "Generate build and test reports"
)
